version: '3'
services:
    laravel.test:
        image: sail-9.0/app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '80:80'
        environment:
            - APP_ENV=local
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=your_database
            - DB_USERNAME=your_username
            - DB_PASSWORD=your_password
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:8.0
        ports:
            - '3306:3306'
        environment:
            - MYSQL_DATABASE=your_database
            - MYSQL_USER=your_username
            - MYSQL_PASSWORD=your_password
            - MYSQL_ROOT_PASSWORD=your_root_password
        volumes:
            - ./mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=your_username
            - PMA_PASSWORD=your_password
        depends_on:
            - mysql

    redis:
        image: redis:alpine
        ports:
            - '6379:6379'
